{config, lib, pkgs, ...}: {
    imports = [
        ./etc/appimage.nix
        ./etc/firewall.nix
        ./etc/gaming.nix
        ./etc/i18n.nix
        ./etc/ssh.nix
        ./firewall/cities_skylines.nix
        ./firewall/kde_connect.nix
        ./firewall/tools.nix
        ./firewall/qbittorrent.nix
        ./hardware/bluetooth.nix
        ./hardware/libinput.nix
        ./hardware/networkmanager.nix
        ./hardware/pipewire.nix
        ./hardware/upower.nix
        ./hardware/misc.nix
        ./hardware/edids.nix
        ./session/sway.nix
        ./session/hyprland.nix
        ./software/firefox.nix
        ./software/greetd.nix
        ./software/lutris.nix
        ./software/steam.nix
        ./software/tailscale.nix
        ./software/utils.nix
        ./software/zsh.nix
        ./virtualisation/docker.nix
        ./virtualisation/virtd.nix
    ];
}
